import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { supabase } from '../lib/supabase';

type Mode = 'income' | 'expense';
type View = 'home' | 'categories' | 'recent';
type Transaction = { id: number; type: Mode; amount: number; category?: string; note: string; date: string; time: string };

const categories = [['餐饮', '◒'], ['购物', '◇'], ['朋友聚餐', '♧'], ['烟酒', '⌁'], ['出行', '↗'], ['娱乐', '✦'], ['医疗健康', '＋'], ['其他', '•••']];
const categoryColors = ['#78977f', '#d1a75b', '#bc8278', '#9aa9a0', '#7d99a6', '#9a8cab', '#c18c79', '#aeb8b0'];
const initialTransactions: Transaction[] = [
  { id: 1, type: 'expense', amount: 42, category: '餐饮', note: '午餐', date: '2026-09-03', time: '12:24' },
  { id: 2, type: 'expense', amount: 186, category: '购物', note: '日常用品', date: '2026-09-02', time: '18:06' },
  { id: 3, type: 'expense', amount: 128, category: '朋友聚餐', note: '和朋友吃饭', date: '2026-09-02', time: '19:40' },
  { id: 4, type: 'expense', amount: 36, category: '烟酒', note: '日常', date: '2026-09-01', time: '09:10' },
  { id: 5, type: 'income', amount: 8500, note: '转入', date: '2026-09-01', time: '08:30' },
  { id: 6, type: 'expense', amount: 76, category: '餐饮', note: '早餐与咖啡', date: '2026-09-01', time: '08:05' },
];

const money = (value: number) => `¥ ${value.toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateLabel = (date: string) => date === '2026-09-03' ? '今天' : date === '2026-09-02' ? '昨天' : date.slice(5).replace('-', '月') + '日';
const fromDbRow = (row: { id: number; type: Mode; amount: number | string; category?: string | null; note?: string | null; occurred_at: string }): Transaction => { const date = row.occurred_at.slice(0, 10); return { id: row.id, type: row.type, amount: Number(row.amount), category: row.category ?? undefined, note: row.note ?? (row.type === 'income' ? '收入' : row.category ?? '支出'), date, time: row.occurred_at.slice(11, 16) }; };

function Donut({ rows, onHover }: { rows: Array<{ name: string; value: number; color: string }>; onHover: (name: string | null) => void }) {
  let offset = 0;
  const total = rows.reduce((sum, row) => sum + row.value, 0);
  return <div className="donut-wrap"><svg className="donut" viewBox="0 0 42 42" role="img" aria-label="本月支出分类占比"><circle cx="21" cy="21" r="15.9155" fill="none" stroke="#e5eae5" strokeWidth="7" />{rows.map((row) => { const pct = total ? row.value / total * 100 : 0; const current = offset; offset += pct; return <circle key={row.name} cx="21" cy="21" r="15.9155" fill="none" stroke={row.color} strokeWidth="7" pathLength="100" strokeDasharray={`${pct} ${100 - pct}`} strokeDashoffset={-current} onMouseEnter={() => onHover(row.name)} onMouseLeave={() => onHover(null)} />; })}</svg><div className="donut-center"><strong>{money(total).replace('.00', '')}</strong><small>总支出</small></div></div>;
}

export default function AccountingApp() {
  const [view, setView] = useState<View>('home');
  const [menuOpen, setMenuOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [mode, setMode] = useState<Mode | null>(null);
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState('餐饮');
  const [transactions, setTransactions] = useState(initialTransactions);
  const [hoveredCategory, setHoveredCategory] = useState<string | null>(null);
  const [selectedMonth, setSelectedMonth] = useState('2026-09');
  const [session, setSession] = useState<{ user: { id: string; email?: string | null } } | null>(null);
  const [authReady, setAuthReady] = useState(false);
  const [authMode, setAuthMode] = useState<'sign-in' | 'sign-up'>('sign-in');
  const [authEmail, setAuthEmail] = useState('');
  const [authPassword, setAuthPassword] = useState('');
  const [authMessage, setAuthMessage] = useState('');
  const [dbMessage, setDbMessage] = useState('');
  useEffect(() => { if (!supabase) { setAuthReady(true); return; } let mounted = true; supabase.auth.getSession().then(({ data }) => { if (mounted) { setSession(data.session as typeof session); setAuthReady(true); } }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next ? next as typeof session : null)); return () => { mounted = false; listener.subscription.unsubscribe(); }; }, []);
  useEffect(() => { if (!supabase || !session) return; supabase.from('transactions').select('id,type,amount,category,note,occurred_at').order('occurred_at', { ascending: false }).then(({ data, error }) => { if (error) { setDbMessage('请先在 Supabase 执行 supabase/schema.sql'); return; } setTransactions((data ?? []).map(fromDbRow)); setDbMessage(''); }); }, [session]);
  const currentMonth = transactions.filter((item) => item.date.startsWith(selectedMonth));
  const income = currentMonth.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amount, 0);
  const expense = currentMonth.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amount, 0);
  const categoryRows = useMemo(() => categories.map(([name], index) => ({ name, value: currentMonth.filter((item) => item.category === name).reduce((sum, item) => sum + item.amount, 0), color: categoryColors[index] })).filter((row) => row.value > 0).sort((a, b) => b.value - a.value), [currentMonth]);
  const openEntry = (next: Mode) => { setMode(next); setAmount(''); setCategory('餐饮'); };
  const append = (value: string) => setAmount((current) => value === '.' && current.includes('.') ? current : current === '0' ? value : current + value);
  const saveEntry = async () => { const numeric = Number(amount); if (!numeric || numeric <= 0 || !mode) return; const now = new Date(); const draft = { type: mode, amount: numeric, category: mode === 'expense' ? category : null, note: mode === 'expense' ? category : '收入', occurred_at: now.toISOString() }; if (supabase && session) { const { data, error } = await supabase.from('transactions').insert({ ...draft, user_id: session.user.id }).select('id,type,amount,category,note,occurred_at').single(); if (error) { setDbMessage(error.message); return; } setTransactions((items) => [fromDbRow(data), ...items]); } else { setTransactions((items) => [{ id: Date.now(), ...draft, date: now.toISOString().slice(0, 10), time: now.toTimeString().slice(0, 5) }, ...items] as Transaction[]); } setMode(null); };
  const navigate = (next: View) => { setView(next); setMenuOpen(false); };
  const submitAuth = async (event: FormEvent) => { event.preventDefault(); setAuthMessage(''); if (!supabase) { setAuthMessage('尚未配置 Supabase'); return; } const result = authMode === 'sign-in' ? await supabase.auth.signInWithPassword({ email: authEmail, password: authPassword }) : await supabase.auth.signUp({ email: authEmail, password: authPassword }); if (result.error) setAuthMessage(result.error.message); else setAuthMessage(authMode === 'sign-up' ? '注册成功，请检查邮箱后登录。' : ''); };

  if (!authReady) return <main className="auth-shell"><div className="auth-card"><span className="eyebrow">MIST LEDGER</span><h1>正在打开账本…</h1></div></main>;
  if (supabase && !session) return <main className="auth-shell"><div className="auth-card"><div className="auth-mark">M</div><p className="eyebrow">MIST LEDGER</p><h1>{authMode === 'sign-in' ? '欢迎回来。' : '开始记录。'}</h1><p className="auth-lede">你的账单只属于你自己。</p><form onSubmit={submitAuth}><label>邮箱<input type="email" value={authEmail} onChange={(e) => setAuthEmail(e.target.value)} placeholder="you@example.com" required /></label><label>密码<input type="password" value={authPassword} onChange={(e) => setAuthPassword(e.target.value)} placeholder="至少 6 位" minLength={6} required /></label>{authMessage && <p className="auth-message">{authMessage}</p>}<button className="auth-submit">{authMode === 'sign-in' ? '登录' : '注册'}</button></form><button className="auth-switch" onClick={() => { setAuthMode(authMode === 'sign-in' ? 'sign-up' : 'sign-in'); setAuthMessage(''); }}>{authMode === 'sign-in' ? '还没有账号？注册' : '已有账号？登录'}</button></div></main>;
  return <main className="app-shell">
    <header className="topbar"><button className={`menu-trigger ${menuOpen ? 'is-open' : ''}`} onClick={() => setMenuOpen(!menuOpen)} aria-label="打开菜单"><i></i><i></i><i></i></button><button className={`profile ${profileOpen ? 'is-expanded' : ''}`} onClick={() => setProfileOpen(!profileOpen)} aria-label="个人记账"><span className="avatar">M</span>{profileOpen && <><span className="profile-label">记账</span>{supabase && session && <span className="logout" onClick={(e) => { e.stopPropagation(); supabase.auth.signOut(); }}>退出</span>}</>}</button></header>
    {menuOpen && <><button className="backdrop" onClick={() => setMenuOpen(false)} aria-label="关闭菜单"></button><aside className="menu-panel"><div className="menu-heading"><span className="eyebrow">MIST LEDGER</span><span className="menu-dot"></span></div><h2>看见你的<br /><em>每一笔</em></h2><nav>{[['⌂', '首页', 'home'], ['◌', '支出分类', 'categories'], ['≡', '最近账单', 'recent']].map(([icon, label, target]) => <button className={view === target ? 'active' : ''} onClick={() => navigate(target as View)} key={target}><span>{icon}</span>{label}<b>↗</b></button>)}</nav><p className="menu-note">安静记录，清楚生活。</p></aside></>}
    {view === 'home' && <><section className="welcome-row"><div><p className="eyebrow">THURSDAY · 03 SEP 2026</p><h1>今天，也记一笔。</h1></div><div className="month-pill"><span>本月</span><strong>2026.09</strong><button aria-label="切换月份">⌄</button></div></section><section className="action-grid"><button className="action-card income" onClick={() => openEntry('income')}><span className="action-icon">＋</span><span className="action-text"><small>QUICK ADD</small><strong>记录收入</strong></span><span className="action-arrow">↗</span></button><button className="action-card expense" onClick={() => openEntry('expense')}><span className="action-icon">−</span><span className="action-text"><small>QUICK ADD</small><strong>记录支出</strong></span><span className="action-arrow">↗</span></button></section><section className="dashboard-grid"><article className="balance-card"><div className="card-top"><span>本月结余</span><span className="live-dot">● 实时</span></div><strong className="balance">{money(income - expense)}</strong><div className="balance-breakdown"><span><small>收入</small><b className="positive">{money(income)}</b></span><span><small>支出</small><b className="negative">{money(expense)}</b></span><span><small>记录</small><b>{currentMonth.length} 笔</b></span></div></article><article className="category-card"><div className="card-top"><span>支出分类</span><button onClick={() => navigate('categories')}>本月 ↗</button></div><div className="donut-layout"><Donut rows={categoryRows} onHover={setHoveredCategory} /><div className="donut-info">{hoveredCategory ? <div className="hover-detail"><small>当前查看</small><strong>{hoveredCategory}</strong><b>{money(categoryRows.find((row) => row.name === hoveredCategory)?.value ?? 0)}</b></div> : <div className="hover-detail muted"><small>悬停图表</small><strong>查看分类占比</strong><b>本月共 {categoryRows.length} 类</b></div>}<div className="mini-legend">{categoryRows.slice(0, 3).map((row) => <span key={row.name}><i style={{ background: row.color }}></i>{row.name}</span>)}</div></div></div></article></section><section className="recent-card home-recent"><div className="card-top"><span>最近账单</span><button onClick={() => navigate('recent')}>全部 ↗</button></div><div className="transactions">{transactions.slice(0, 5).map((item) => <TransactionRow item={item} key={item.id} />)}</div><div className="today-mark"><span></span>今天 · 2026年9月3日</div></section><section className="voice-card"><div className="voice-orb">⌁</div><div><p className="eyebrow">COMING SOON</p><h2>说一句，记一笔</h2><p>未来可以直接说出消费内容，系统会帮你识别金额与分类。</p></div><button disabled aria-label="语音输入暂未开放">麦克风 <span>·</span></button></section></>}
    {view === 'categories' && <CategoryView transactions={transactions} selectedMonth={selectedMonth} onSelectMonth={setSelectedMonth} onBack={() => navigate('home')} />}
    {view === 'recent' && <RecentView transactions={transactions} onBack={() => navigate('home')} />}
    {mode && <div className="modal-backdrop" onClick={() => setMode(null)}><section className="entry-modal" onClick={(e) => e.stopPropagation()}><div className="modal-head"><div><span className={`modal-kicker ${mode}`}>{mode === 'income' ? 'INCOME' : 'EXPENSE'}</span><h2>{mode === 'income' ? '记录一笔收入' : '记录一笔支出'}</h2></div><button onClick={() => setMode(null)} aria-label="关闭">×</button></div><div className="amount-input"><span>¥</span><input autoFocus inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^\d.]/g, ''))} placeholder="0.00" aria-label="金额" /></div>{mode === 'expense' && <div className="modal-categories">{categories.map(([name, icon]) => <button className={category === name ? 'selected' : ''} onClick={() => setCategory(name)} key={name}><span>{icon}</span>{name}</button>)}</div>}<div className="keypad">{['1','2','3','4','5','6','7','8','9','.','0','⌫'].map((key) => <button onClick={() => key === '⌫' ? setAmount(amount.slice(0, -1)) : append(key)} key={key}>{key}</button>)}</div><button className="save-button" onClick={saveEntry}>{mode === 'income' ? '保存收入' : `保存支出 · ${category}`}</button></section></div>}
  </main>;
}

function TransactionRow({ item }: { item: Transaction }) { return <div className="transaction"><span className={`tx-icon ${item.type === 'income' ? 'salary' : item.category === '购物' ? 'shop' : 'food'}`}>{item.type === 'income' ? '＋' : item.category === '购物' ? '◇' : '◒'}</span><span><b>{item.note}</b><small>{dateLabel(item.date)} · {item.time} · {item.type === 'income' ? '收入' : item.category}</small></span><strong className={item.type === 'income' ? 'positive' : 'negative'}>{item.type === 'income' ? '＋' : '−'} {money(item.amount)}</strong></div>; }

function CategoryView({ transactions, selectedMonth, onSelectMonth, onBack }: { transactions: Transaction[]; selectedMonth: string; onSelectMonth: (month: string) => void; onBack: () => void }) { const months = ['2026-09', '2026-08', '2026-07', '2026-06']; const monthRows = months.map((month) => { const rows = transactions.filter((item) => item.date.startsWith(month)); return { month, income: rows.filter((item) => item.type === 'income').reduce((s, i) => s + i.amount, 0), expense: rows.filter((item) => item.type === 'expense').reduce((s, i) => s + i.amount, 0), count: rows.length }; }); const selected = monthRows.find((item) => item.month === selectedMonth)!; return <section className="subpage"><button className="back-link" onClick={onBack}>← 返回首页</button><div className="subpage-head"><div><p className="eyebrow">SPENDING ARCHIVE</p><h1>支出分类</h1><p>按月份看看钱都去了哪里。</p></div><span className="archive-icon">◌</span></div><div className="month-tabs">{monthRows.map((item) => <button className={item.month === selectedMonth ? 'selected' : ''} onClick={() => onSelectMonth(item.month)} key={item.month}><small>{item.month.slice(0, 4)}</small><strong>{item.month.slice(5)}月</strong></button>)}</div><article className="month-summary"><div><span>{selected.month.slice(0, 4)}年{selected.month.slice(5)}月</span><strong>{money(selected.expense)}</strong><small>支出 · {selected.count} 笔记录</small></div><div className="month-summary-side"><span>收入 <b className="positive">{money(selected.income)}</b></span><span>结余 <b>{money(selected.income - selected.expense)}</b></span></div></article><div className="month-grid">{monthRows.map((item) => <button className={`month-card ${selectedMonth === item.month ? 'selected' : ''}`} onClick={() => onSelectMonth(item.month)} key={item.month}><div><small>{item.month.slice(0, 4)}</small><h3>{item.month.slice(5)}月</h3></div><div className="month-card-values"><span>支出 <b className="negative">{money(item.expense)}</b></span><span>收入 <b className="positive">{money(item.income)}</b></span></div><i>↗</i></button>)}</div></section>; }

function RecentView({ transactions, onBack }: { transactions: Transaction[]; onBack: () => void }) { return <section className="subpage"><button className="back-link" onClick={onBack}>← 返回首页</button><div className="subpage-head"><div><p className="eyebrow">ALL TRANSACTIONS</p><h1>最近账单</h1><p>每一笔，都有迹可循。</p></div><span className="archive-icon">≡</span></div><article className="all-transactions"><div className="all-transactions-head"><span>全部记录</span><b>{transactions.length} 笔</b></div>{transactions.map((item) => <TransactionRow item={item} key={item.id} />)}</article></section>; }
